# Generated by Django 2.0.7 on 2018-09-29 06:40

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import rooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', django.contrib.postgres.fields.ranges.DateTimeRangeField(db_index=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('refunded', 'Refunded')], default='created', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], max_length=6)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('location', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('cleanliness', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('communication', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('num_guests', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('bed_rooms', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('beds', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('bath_rooms', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('is_bath_private', models.BooleanField(default=True)),
                ('lat', models.CharField(blank=True, max_length=250, null=True)),
                ('lan', models.CharField(blank=True, max_length=250, null=True)),
                ('amenities', rooms.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('TV', 'TV'), ('WiFi', 'WiFi'), ('Iron', 'Iron'), ('Essentials', 'Essentials'), ('Air conditioning', 'Air conditioning'), ('Kitchen', 'Kitchen')], max_length=250), blank=True, null=True, size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('about_place', models.TextField(blank=True, null=True)),
                ('guest_access', models.TextField(blank=True, null=True)),
                ('interaction', models.TextField(blank=True, null=True)),
                ('other_notes', models.TextField(blank=True, null=True)),
                ('get_around', models.TextField(blank=True, null=True)),
                ('for_children', models.BooleanField(default=True)),
                ('for_infaints', models.BooleanField(default=True)),
                ('for_pets', models.BooleanField(default=True)),
                ('smooking', models.BooleanField(default=True)),
                ('parties', models.BooleanField(default=True)),
                ('checkin_from', models.CharField(blank=True, default='FLEX', max_length=5, null=True)),
                ('checkin_to', models.CharField(blank=True, default='FLEX', max_length=5, null=True)),
                ('min_stay', models.PositiveSmallIntegerField(default=1)),
                ('max_stay', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('first_offer', models.BooleanField(default=True)),
                ('weekly_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('room_type', models.CharField(choices=[('PR', 'Private Room'), ('EH', 'Entire House')], default='PR', max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instant', models.BooleanField(default=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='image',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.Room'),
        ),
    ]
