# Generated by Django 2.0.7 on 2018-09-13 08:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], max_length=6)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('num_guests', models.PositiveSmallIntegerField(default=1)),
                ('bed_rooms', models.PositiveSmallIntegerField(default=1)),
                ('beds', models.PositiveSmallIntegerField(default=1)),
                ('bath_rooms', models.PositiveSmallIntegerField(default=0)),
                ('is_bath_private', models.BooleanField(default=True)),
                ('lat', models.CharField(blank=True, max_length=250, null=True)),
                ('lan', models.CharField(blank=True, max_length=250, null=True)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('TV', 'TV'), ('WiFi', 'WiFi'), ('Iron', 'Iron'), ('Essentials', 'Essentials'), ('Air conditioning', 'Air conditioning'), ('Kitchen', 'Kitchen')], max_length=250), size=None)),
                ('description', models.TextField()),
                ('about_place', models.TextField()),
                ('guest_access', models.TextField()),
                ('interaction', models.TextField()),
                ('other_notes', models.TextField()),
                ('get_around', models.TextField()),
                ('for_children', models.BooleanField(default=True)),
                ('for_infaints', models.BooleanField(default=True)),
                ('for_pets', models.BooleanField(default=True)),
                ('smooking', models.BooleanField(default=True)),
                ('parties', models.BooleanField(default=True)),
                ('checkin_from', models.CharField(default='FLEX', max_length=5)),
                ('checkin_to', models.CharField(default='FLEX', max_length=5)),
                ('min_stay', models.PositiveSmallIntegerField(default=1)),
                ('max_stay', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('first_offer', models.BooleanField(default=True)),
                ('weekly_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('room_type', models.CharField(choices=[('PR', 'Private Room'), ('EH', 'Entire House')], max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instant', models.BooleanField(default=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='image',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.Room'),
        ),
    ]
