# Generated by Django 2.0.7 on 2018-09-13 08:37

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='about_place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=rooms.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('TV', 'TV'), ('WiFi', 'WiFi'), ('Iron', 'Iron'), ('Essentials', 'Essentials'), ('Air conditioning', 'Air conditioning'), ('Kitchen', 'Kitchen')], max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='bath_rooms',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_rooms',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='checkin_from',
            field=models.CharField(blank=True, default='FLEX', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='checkin_to',
            field=models.CharField(blank=True, default='FLEX', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='get_around',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='guest_access',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='interaction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='monthly_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_guests',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('PR', 'Private Room'), ('EH', 'Entire House')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='weekly_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
