# Generated by Django 2.0.7 on 2018-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='cleanliness',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='communication',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True),
        ),
    ]
