# Generated by Django 2.0.7 on 2018-09-13 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('response_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('response_time', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_super', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('id_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('fb_account', models.BooleanField(default=False)),
                ('google_account', models.BooleanField(default=False)),
                ('emergency_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
